name: web_app
description: Simple web-based voting app

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^5.0.3
  provider: ^3.0.0+1

flutter:
  uses-material-design: true