name: web_app
description: Simple web-based voting app

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: ^5.0.3

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    path: ../../../official_github_repos/flutter_web/packages/flutter_web
  flutter_web_ui:
    path: ../../../official_github_repos/flutter_web/packages/flutter_web_ui