name: mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.5
  provider: ^3.0.0
  fireworks: ^0.9.3
  flutter_blue:
    git: 
      url: https://github.com/efortuna/flutter_blue
  flutter_vector_icons: ^0.1.0
  font_awesome_flutter: ^8.4.0
  flutter_spinkit: ^3.1.0
  shimmer: ^1.0.0
  progress_indicators: #^0.1.4
    git:
      url: https://github.com/efortuna/progress_indicators

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/diagonal_rainbow_gradient.jpg
    - assets/fire.jpg
    - assets/snow_sparkle.jpg
    - assets/colorful_lights.jpg
    - assets/ball_pit.jpg
    - assets/light_bulb.png 
