name: mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.5
  provider: ^3.0.0
  flutter_blue:
    git: 
      url: https://github.com/efortuna/flutter_blue
  flutter_vector_icons: ^0.1.0
  font_awesome_flutter: ^8.4.0
  flutter_spinkit: ^3.1.0
  shimmer: ^1.0.0
  progress_indicators: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/diagonal_rainbow_gradient.jpg
    - assets/diagonal_rainbow_gradient2.jpg
    - assets/rainbow_gradient.png
  fonts:
    - family: MountainsOfChristmas
      fonts:
        - asset: assets/fonts/Mountains_of_Christmas/MountainsofChristmas-Bold.ttf
        - asset: assets/fonts/Mountains_of_Christmas/MountainsofChristmas-Regular.ttf
          style: normal
    - family: SigmarOne
      fonts:
        - asset: assets/fonts/Sigmar_One/SigmarOne-Regular.ttf
          style: normal